"""
Factor Mining Agent

Refactoring goals:
1. No longer use MCP client
2. GP mining changed to local functional calls
3. Retain LLM's ability to generate seed factors and recommend operators
"""
from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional, Tuple

from Agent.prompts import (
    FACTOR_TEMPLATE_GENERATION_PROMPT,
    VALID_FEATURES,
    VALID_OPERATORS,
)
from Agent.services.local_gp_service import LocalGPService
from utils.file_process import get_top_factors_from_gp_json


class FactorMiningAgent:
    """Responsible for single-round GP factor mining."""

    def __init__(self, llm_service) -> None:
        self.llm = llm_service
        self.gp_service = LocalGPService()

    def process(
        self,
        previous_selection_result: Optional[Dict[str, Any]] = None,
        mining_feedback: Optional[Dict[str, Any]] = None,
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        """
        Execute the factor mining process.

        Returns:
        1. GP output factor list
        2. Current round execution record
        """
        merged_seed_factors = self._prepare_seed_factors(mining_feedback)
        factor_file, selection_result = self._call_gp_training(
            seed_factors=merged_seed_factors,
            previous_seed=self._extract_previous_seed(previous_selection_result),
            iteration=int(mining_feedback.get("iteration", 0)) if mining_feedback else 0,
        )

        factors_list = get_top_factors_from_gp_json(
            json_file_path=factor_file,
            top_n=200,
            ic_threshold=None,
        )
        return factors_list, selection_result

    def _prepare_seed_factors(self, mining_feedback: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Aggregate seed factors from feedback and newly generated by LLM."""
        if not mining_feedback:
            return []

        suggested_seeds = mining_feedback.get("suggested_seeds", []) or []
        llm_generated_seeds: List[Dict[str, Any]] = []

        llm_result = self.generate_factor_templates_with_llm(
            mining_feedback=mining_feedback,
            existing_seeds=suggested_seeds,
        )
        factor_templates = llm_result.get("factor_templates", [])
        llm_generated_seeds = self._convert_templates_to_seeds(factor_templates)

        valid_suggested_seeds = self._filter_valid_seeds(
            suggested_seeds,
            source_name="feedback seed factors",
        )
        valid_llm_seeds = self._filter_valid_seeds(
            llm_generated_seeds,
            source_name="LLM newly generated seed factors",
        )

        all_seeds = valid_suggested_seeds + valid_llm_seeds
        mining_feedback["suggested_seeds"] = all_seeds
        mining_feedback["llm_generated_count"] = len(valid_llm_seeds)
        return all_seeds

    def _call_gp_training(
        self,
        seed_factors: Optional[List[Dict[str, Any]]] = None,
        previous_seed: Optional[int] = None,
        iteration: int = 0,
        instruments: str = "csi300",
        train_end_year: int = 2020,
        cuda: str = "0",
    ) -> Tuple[str, Dict[str, Any]]:
        """
        Direct local GP training entry point.

        No longer uses MCP here; instead, calls directly via local service functions.
        """
        new_seed = (previous_seed + 1) if previous_seed is not None else iteration
        config_params = {
            "instruments": instruments,
            "seed": new_seed,
            "train_end_year": train_end_year,
            "freq": "day",
            "cuda": cuda,
            "target_horizon_days": 10,
            "seed_factors": seed_factors or [],
        }

        selection_result = {
            "runner": "local_gp_service",
            "reason": f"Iteration {iteration} GP local execution, using {len(seed_factors or [])} seed factors",
            "suggested_parameters": {
                "seed": new_seed,
                "config_params": config_params,
            },
            "seed_factors_count": len(seed_factors or []),
        }

        factor_file = self.gp_service.run_gp(
            config_params=config_params,
            task_name=f"gp_iteration_{iteration}_seed_{new_seed}",
        )
        return factor_file, selection_result

    def generate_factor_templates_with_llm(
        self,
        mining_feedback: Dict[str, Any],
        existing_seeds: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        """Generate new seed factor templates via LLM based on feedback."""
        if not self.llm:
            return {
                "factor_templates": [],
                "generation_strategy": "LLM not configured, skipping template generation",
            }

        iteration = mining_feedback.get("iteration", 0)
        pool_weaknesses = mining_feedback.get("pool_weaknesses", [])
        suggested_directions = mining_feedback.get("suggested_directions", [])
        gp_strategy_hints = mining_feedback.get("gp_strategy_hints", {})
        convergence_info = mining_feedback.get("convergence_info", {})

        pool_weaknesses_str = "\n".join([f"- {item}" for item in pool_weaknesses]) if pool_weaknesses else "None"
        suggested_directions_str = (
            "\n".join([f"- {item}" for item in suggested_directions])
            if suggested_directions
            else "None"
        )
        gp_strategy_hints_str = (
            json.dumps(gp_strategy_hints, indent=2, ensure_ascii=False)
            if gp_strategy_hints
            else "None"
        )
        convergence_info_str = (
            json.dumps(convergence_info, indent=2, ensure_ascii=False)
            if convergence_info
            else "None"
        )

        if existing_seeds:
            existing_seeds_str = "\n".join(
                [
                    f"- {seed.get('expression', '')} (IC: {seed.get('ic', 'N/A')})"
                    for seed in existing_seeds[:10]
                ]
            )
        else:
            existing_seeds_str = "None"

        prompt = FACTOR_TEMPLATE_GENERATION_PROMPT.format(
            iteration=iteration,
            pool_weaknesses=pool_weaknesses_str,
            suggested_directions=suggested_directions_str,
            gp_strategy_hints=gp_strategy_hints_str,
            convergence_info=convergence_info_str,
            existing_seeds=existing_seeds_str,
        )

        try:
            response = self.llm.call(prompt=prompt, stream=False)
            result = self.llm.parse_json_response(response)
            return {
                "factor_templates": result.get("factor_templates", []),
                "generation_strategy": result.get("generation_strategy", ""),
            }
        except Exception as exc:
            return {
                "factor_templates": [],
                "generation_strategy": f"LLM call failed: {exc}",
            }

    def _convert_templates_to_seeds(self, factor_templates: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Convert LLM templates to GP-acceptable seed factor format."""
        seeds: List[Dict[str, Any]] = []
        for template in factor_templates:
            expression = template.get("expression", "")
            if not expression:
                continue
            seeds.append(
                {
                    "expression": expression,
                    "ic": 0.0,
                    "rank_ic": 0.0,
                    "category": template.get("category", "unknown"),
                    "description": template.get("description", ""),
                    "source": "llm_generated",
                }
            )
        return seeds

    def _filter_valid_seeds(
        self,
        seeds: List[Dict[str, Any]],
        source_name: str,
    ) -> List[Dict[str, Any]]:
        """Filter out seed factors that do not meet GP operator constraints."""
        valid_seeds: List[Dict[str, Any]] = []
        invalid_count = 0

        for seed in seeds:
            expression = seed.get("expression", "")
            if self._validate_factor_expression(expression):
                valid_seeds.append(seed)
            else:
                invalid_count += 1

        if invalid_count > 0:
            print(f"[FactorMiningAgent] {source_name} filtered out {invalid_count} invalid expressions")
        return valid_seeds

    def _validate_factor_expression(self, expression: str) -> bool:
        """Verify that the expression only uses fields and operators currently supported by GP."""
        if not expression or not isinstance(expression, str):
            return False

        operator_pattern = r"([A-Za-z_][A-Za-z0-9_]*)\s*\("
        found_operators = set(re.findall(operator_pattern, expression))
        feature_pattern = r"\b(open_|close|high|low|volume|vwap)\b"
        found_features = set(re.findall(feature_pattern, expression))

        invalid_operators = found_operators - VALID_OPERATORS
        if invalid_operators:
            return False

        invalid_features = found_features - VALID_FEATURES
        if invalid_features:
            return False

        if not found_operators and not found_features:
            return False

        return True

    @staticmethod
    def _extract_previous_seed(previous_selection_result: Optional[Dict[str, Any]]) -> Optional[int]:
        """Extract the random seed used in the previous round."""
        if not previous_selection_result:
            return None

        suggested_parameters = previous_selection_result.get("suggested_parameters", {})
        seed = suggested_parameters.get("seed")
        try:
            return int(seed)
        except (TypeError, ValueError):
            return None
